### ISSUE TITLE
Unable to make prefab-debug on Windows Subsytem for linux

### ISSUE THREAD

**Issue by abhinaypandey02** [efroemling/ballistica#136]
Followed all the steps provided in Getting Started section.
When executing `make prefab-debug`, the following errors show up:

`Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/pcommand", line 65, in <module>
  File "tools/pcommand", line 65, in <module>
Traceback (most recent call last):
  File "tools/pcommand", line 65, in <module>
Traceback (most recent call last):
  File "tools/pcommand", line 65, in <module>
Traceback (most recent call last):
  File "tools/pcommand", line 65, in <module>
    pcommand_main(globals())
    pcommand_main(globals())
  File "/mnt/d/ballistica/tools/efrotools/pcommand.py", line 74, in pcommand_main
  File "/mnt/d/ballistica/tools/efrotools/pcommand.py", line 74, in pcommand_main
    pcommand_main(globals())
  File "/mnt/d/ballistica/tools/efrotools/pcommand.py", line 74, in pcommand_main
    pcommand_main(globals())
  File "/mnt/d/ballistica/tools/efrotools/pcommand.py", line 74, in pcommand_main
    pcommand_main(globals())
  File "/mnt/d/ballistica/tools/efrotools/pcommand.py", line 74, in pcommand_main
    funcs[sys.argv[1]]()
    funcs[sys.argv[1]]()
    funcs[sys.argv[1]]()
  File "/mnt/d/ballistica/tools/batools/pcommand.py", line 475, in efrocache_get
  File "/mnt/d/ballistica/tools/batools/pcommand.py", line 475, in efrocache_get
    funcs[sys.argv[1]]()
  File "/mnt/d/ballistica/tools/batools/pcommand.py", line 475, in efrocache_get
  File "/mnt/d/ballistica/tools/batools/pcommand.py", line 475, in efrocache_get
    funcs[sys.argv[1]]()
  File "/mnt/d/ballistica/tools/batools/pcommand.py", line 475, in efrocache_get
    get_target(sys.argv[2])
  File "/mnt/d/ballistica/tools/efrotools/efrocache.py", line 75, in get_target
    get_target(sys.argv[2])
  File "/mnt/d/ballistica/tools/efrotools/efrocache.py", line 75, in get_target
    get_target(sys.argv[2])
    get_target(sys.argv[2])
  File "/mnt/d/ballistica/tools/efrotools/efrocache.py", line 75, in get_target
  File "/mnt/d/ballistica/tools/efrotools/efrocache.py", line 75, in get_target
    get_target(sys.argv[2])
  File "/mnt/d/ballistica/tools/efrotools/efrocache.py", line 75, in get_target
    raise RuntimeError(f'Path not found in efrocache: {path}')
    raise RuntimeError(f'Path not found in efrocache: {path}')
RuntimeError: Path not found in efrocache: assets/build/windows/Win32/Lib/_bootlocale.py
RuntimeError: Path not found in efrocache: assets/build/windows/Win32/Lib/_compression.py`

The list is long but the rest are the same errors for different files in  assets/build/windows/Win32/Lib/ directory

**Comment by abhinaypandey02** [comment]
I figured it out myself. 
In the makefile the windows version is hard-coded as `Win32`. But the cachemap has no entries for Win32, rather it has paths like
`assets/build/windows/x64/Lib/symbol.py`. To fix this I had to manually edit the makefile and change Line 330 `PREFAB_WINDOWS_PLATFORM = Win32` to `PREFAB_WINDOWS_PLATFORM = x64`.

This seems like a bug that should be looked into

**Comment by abhinaypandey02** [comment]
Another issue popped up which maybe because of the above mentioned workaround. Following the above mentioned steps did everything fine with no errors. But at the final step of running the game `make prefab-release` reports `The Application was Unable to Start Correctly (0xc000007b)` while ``make prefab-debug` reports `MSVCP140D.dll` (The file is in the same directory and being read by the release file but not the debug file.) 
I am not starting a new issue because these maybe linked up.

**Comment by abhinaypandey02** [comment]
Problem fixed in the recent commit, but the problem for missing DLL coming up. New issue will be started for that
