### ISSUE TITLE
Error BombSquad 1.5

### ISSUE THREAD

**Issue by JoseANG3L** [efroemling/ballistica#2]
This is the error that I have.

`joseang3l@ubuntu:~/ballistica$ make prefab-debug
make[1]: Entering directory '/home/joseang3l/ballistica'
make[2]: Entering directory '/home/joseang3l/ballistica/assets'
Downloading asset starter-cache...
/bin/sh: 1: curl: not found
Traceback (most recent call last):
  File "../tools/snippets", line 874, in <module>
    snippets_main(globals())
  File "/home/joseang3l/ballistica/tools/efrotools/snippets.py", line 82, in snippets_main
    funcs[sys.argv[1]]()
  File "../tools/snippets", line 661, in warm_start_asset_build
    warm_start_cache()
  File "/home/joseang3l/ballistica/tools/efrotools/efrocache.py", line 344, in warm_start_cache
    run(f'curl {BASE_URL}startercache.tar.xz > startercache.tar.xz')
  File "/home/joseang3l/ballistica/tools/efrotools/__init__.py", line 146, in run
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'curl https://files.ballistica.net/cache/ba1/startercache.tar.xz > startercache.tar.xz' returned non-zero exit status 127.
Makefile:51: recipe for target 'cmake' failed
make[2]: *** [cmake] Error 1
make[2]: Leaving directory '/home/joseang3l/ballistica/assets'
Makefile:59: recipe for target 'assets-cmake' failed
make[1]: *** [assets-cmake] Error 2
make[1]: Leaving directory '/home/joseang3l/ballistica'
Traceback (most recent call last):
  File "tools/snippets", line 874, in <module>
    snippets_main(globals())
  File "/home/joseang3l/ballistica/tools/efrotools/snippets.py", line 82, in snippets_main
    funcs[sys.argv[1]]()
  File "tools/snippets", line 845, in make_prefab
    run(f'make {target}')
  File "/home/joseang3l/ballistica/tools/efrotools/__init__.py", line 146, in run
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'make prefab-linux-debug' returned non-zero exit status 2.
Makefile:118: recipe for target 'prefab-debug' failed
make: *** [prefab-debug] Error 1
`

**Comment by efroemling** [comment]
It looks like your build is failing on the command 'curl https://files.ballistica.net/cache/ba1/startercache.tar.xz' <https://files.ballistica.net/cache/ba1/startercache.tar.xz'>
Can you run that command yourself in a terminal and see if it succeeds? Perhaps you don’t have the ‘curl’ command available?

**Comment by JoseANG3L** [comment]
Ok I'll try

**Comment by JoseANG3L** [comment]
First.
Thank you very much, if it worked, I did not have curl installed, now it works perfectly.

Second.
I followed all the steps shown on the page https://github.com/efroemling/ballistica/wiki/Getting-Started and that was the result it gave me, that happened to me in Windows and Ubuntu.

**Comment by efroemling** [comment]
Good to know! I’ll modify the environment checks to issue a warning if ‘curl’ is not present.

**Comment by efroemling** [comment]
Added a check for 'curl' in commit https://github.com/efroemling/ballistica/commit/173a0ffa15eb9df464d60315fe6f069d52521d82
