### ISSUE TITLE
Broken buildsystem

### ISSUE THREAD

**Issue by Dliwk** [efroemling/ballistica#26]
[Last commit](https://github.com/efroemling/ballistica/commit/5114280d0a3c64cba43fce40ca628f3926573bef) broke buildsystem (target __prefab-*__ doesn't work):

```
$ make prefab-debug

make[1]: *** No rule to make target 'PrefabTarget.DEBUG'.  Stop.
make[1]: Entering directory '/home/roman/trash/build/fixes/ballistica'
make[1]: Leaving directory '/home/roman/trash/build/fixes/ballistica'
Traceback (most recent call last):
  File "tools/snippets", line 565, in <module>
    snippets_main(globals())
  File "/home/roman/trash/build/fixes/ballistica/tools/efrotools/snippets.py", line 82, in snippets_main
    funcs[sys.argv[1]]()
  File "tools/snippets", line 537, in make_prefab
    batools.build.make_prefab(target)
  File "/home/roman/trash/build/fixes/ballistica/tools/batools/build.py", line 469, in make_prefab
    run(f'make {target}')
  File "/home/roman/trash/build/fixes/ballistica/tools/efrotools/__init__.py", line 149, in run
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'make PrefabTarget.DEBUG' returned non-zero exit status 2.
make: *** [Makefile:118: prefab-debug] Error 1
```

**Comment by efroemling** [comment]
Thanks for the heads up; just pushed commit eb821126ac137898687834c8be2ad3368717a5c3 with a fix.
