### ISSUE TITLE
Problem with locales

### ISSUE THREAD

**Issue by NullWizard** [efroemling/ballistica#29]
Locales don't work. Build on the Windows 10. I did everything according to the instructions from the wiki.

```
Resorting to fallback language (English)
ERROR: error setting language to english fallback
  root call: <unavailable>
  context: <empty context>
  real-time: 8016
  sim-time: <unavailable>
  base-time: <unavailable>
PRINTED-FROM:
  File "\\wsl$\Ubuntu-18.04\home\nullwizard\ballistica\build\prefab\windows\release\ba_data\python\ba\_lang.py", line 35
0, in get_resource
    'error setting language to english fallback')
  File "\\wsl$\Ubuntu-18.04\home\nullwizard\ballistica\build\prefab\windows\release\ba_data\python\ba\_error.py", line 1
68, in print_exception
    stackstr = ''.join(traceback.format_stack())
EXCEPTION:
  Traceback (most recent call last):
    File "\\wsl$\Ubuntu-18.04\home\nullwizard\ballistica\build\prefab\windows\release\ba_data\python\ba\_lang.py", line
335, in get_resource
      store_to_config=False)
    File "\\wsl$\Ubuntu-18.04\home\nullwizard\ballistica\build\prefab\windows\release\ba_data\python\ba\_lang.py", line
223, in setlanguage
      lenglishvalues = json.loads(infile.read())
    File "\\wsl$\Ubuntu-18.04\home\nullwizard\ballistica\build\prefab\windows\release\Lib\encodings\cp1251.py", line 23,
 in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 69200: character maps to <undefined>

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "\\wsl$\Ubuntu-18.04\home\nullwizard\ballistica\build\prefab\windows\release\ba_data\python\ba\_lang.py", line
347, in get_resource
      store_to_config=False)
    File "\\wsl$\Ubuntu-18.04\home\nullwizard\ballistica\build\prefab\windows\release\ba_data\python\ba\_lang.py", line
223, in setlanguage
      lenglishvalues = json.loads(infile.read())
    File "\\wsl$\Ubuntu-18.04\home\nullwizard\ballistica\build\prefab\windows\release\Lib\encodings\cp1251.py", line 23,
 in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 69200: character maps to <undefined>
GetResource failed for 'watchWindow.titleText'
```

**Comment by efroemling** [comment]
Thanks for the heads-up. Did you get this error on launch? Or when switching to a specific language? And what language is your OS set to?

**Comment by NullWizard** [comment]
I got this error on first start. The Russian language was automatically set in the game. Then I changed to English. But both Russian and English do not work. OS language is Russian.

**Comment by efroemling** [comment]
Oh cool; I am seeing this problem as well. Hopefully that'll make it easy to fix...

**Comment by efroemling** [comment]
Ok I just pushed a new commit which I think should fix this. Can you do a pull and give it another try?

**Comment by NullWizard** [comment]
Great, all works.
