### ISSUE TITLE
module 'typing' has no attribute 'get_origin'

### ISSUE THREAD

**Issue by 1357koushik** [efroemling/ballistica#310]
## Description
```
 Traceback (most recent call last):
   File "bombsquad_server", line 25, in <module>
     from bacommon.servermanager import ServerConfig, StartServerModeCommand
   File "dist/ba_data/python/bacommon/servermanager.py", line 17, in <module>
     @dataclass
   File "dist/ba_data/python/efro/dataclassio.py", line 301, in ioprepped
     ioprep(cls)
   File "dist/ba_data/python/efro/dataclassio.py", line 289, in ioprep
     PrepSession(explicit=True).prep_dataclass(cls, recursion_level=0)
   File "dist/ba_data/python/efro/dataclassio.py", line 401, in prep_dataclass
     recursion_level=recursion_level + 1)
   File "dist/ba_data/python/efro/dataclassio.py", line 421, in prep_type
     origin = _get_origin(anntype)
   File "dist/ba_data/python/efro/dataclassio.py", line 618, in _get_origin
     origin = typing.get_origin(anntype)
 AttributeError: module 'typing' has no attribute 'get_origin'
```
## Steps to reproduce
1. python bombsquad_server
2. bug
## Extra
i used in heroku

**Comment by Voxel25** [comment]
Python version?
