### ISSUE TITLE
Makefile:477: recipe for target 'format' failed

### ISSUE THREAD

**Issue by Awesome-Logic** [efroemling/ballistica#36]
The `make format` seems to have some error with workers.

`root@ip-172-31-32-36:~/Server/ballistica# make format
make[1]: Entering directory '/root/Server/ballistica'
Traceback (most recent call last):
  File "tools/snippets", line 582, in <module>
    snippets_main(globals())
  File "/root/Server/ballistica/tools/efrotools/snippets.py", line 73, in snippets_main
    funcs[sys.argv[1]]()
  File "/root/Server/ballistica/tools/efrotools/snippets.py", line 199, in formatcode
    code.formatcode(PROJROOT, full)
  File "/root/Server/ballistica/tools/efrotools/code.py", line 75, in formatcode
    2) as executor:
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 129, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0
Makefile:487: recipe for target 'format-code' failed
make[1]: *** [format-code] Error 1
make[1]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "tools/snippets", line 582, in <module>
    snippets_main(globals())
  File "/root/Server/ballistica/tools/efrotools/snippets.py", line 73, in snippets_main
    funcs[sys.argv[1]]()
  File "/root/Server/ballistica/tools/efrotools/snippets.py", line 206, in formatscripts
    code.formatscripts(PROJROOT, full)
  File "/root/Server/ballistica/tools/efrotools/code.py", line 186, in formatscripts
    with ThreadPoolExecutor(max_workers=cpu_count() // 2) as executor:
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 129, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0
Makefile:495: recipe for target 'format-scripts' failed
make[1]: *** [format-scripts] Error 1
make[1]: Leaving directory '/root/Server/ballistica'
Makefile:477: recipe for target 'format' failed
make: *** [format] Error 2`

**Comment by efroemling** [comment]
Ok, my guess is that you are running with a single cpu core which broke my math for how many cpus to use :)

I just fixed that and pushed a commit: c3b5a8807c5d04ee3f57f98bbe07a058804c28b5

Can you give it a try? With one cpu, `make format` might take a while the first time through, but after that it should only need to re-run on files when they change so should be much faster.

**Comment by Awesome-Logic** [comment]
Yeah, I'm was running it on a single core cloud machine. I just tried again and it worked! Thanks :)
