### ISSUE TITLE
bombsquad in my Mac not connect to internet 

### ISSUE THREAD

**Issue by kingrty** [efroemling/ballistica#362]
<img width="804" alt="Screen Shot 1400-11-18 at 19 06 46" src="https://user-images.githubusercontent.com/99199271/152822261-54cf2166-254e-43d8-91e5-fcf317929903.png">

**Comment by Dliwk** [comment]
I met another guy (on Windows) who ran into the same, but it works for me (checked both windows and linux versions), so perhaps we should collect more conditions of this...

**Comment by kingrty** [comment]
> Is any other network-related functionality working? Like the public game browser or tournament list? Or nothing at all?

does give id  
tournament and servers not show but I can join with ip servers

**Comment by Freaku17** [comment]
Faced similar issue on Android build 1.6.8 (20458). I tried with my wifi and Mobile data, both didn't seem to work. Since it never logged in, the whole shop was showing tickets ? and tournaments unavailable. Public list also never showed up, connected servers with IP worked. Later I installed back 1.6.4

**Comment by efroemling** [comment]
> Faced similar issue on Android build 1.6.8 (20458). I tried with my wifi and Mobile data, both didn't seem to work. Since it never logged in, the whole shop was showing tickets ? and tournaments unavailable. Public list also never showed up, connected servers with IP worked. Later I installed back 1.6.4 and it had logged me immediately.

The latest Android builds (as of 20459) currently have broken networking. I'll try to get it fixed tomorrow and I added a warning to the builds page in the meantime. However other platforms should be working. @kingrty can you try the latest Mac build and confirm if networking is still not working for you?

**Comment by kingrty** [comment]
> > Faced similar issue on Android build 1.6.8 (20458). I tried with my wifi and Mobile data, both didn't seem to work. Since it never logged in, the whole shop was showing tickets ? and tournaments unavailable. Public list also never showed up, connected servers with IP worked. Later I installed back 1.6.4 and it had logged me immediately.
> 
> The latest Android builds (as of 20459) currently have broken networking. I'll try to get it fixed tomorrow and I added a warning to the builds page in the meantime. However other platforms should be working. @kingrty can you try the latest Mac build and confirm if networking is still not working for you?


Hi sorry it does not work again
Watch this video
https://usaupload.com/shared/8751y9xzo4yfu5e03ri0o0on8lqo7o9e43gihwc8q8z7mhg3umtmu-7ttzjrtri8xrg_27w16ao1uj99zpf7_s85h3_ctlf2-s7o3r5odluymgnv5kiia89m-xbb8s_l

**Comment by efroemling** [comment]
Update:
Android networking should now be working again in the newer 1.6.9 build. Please let me know if you run into any more problems with it.

Tomorrow I plan to add a 'network diagnostics' page under advanced settings to help debug issues like this. Hopefully that'll tell us what's going wrong with the Mac version you're trying.

**Comment by kingrty** [comment]
so you fixing it in new version?

**Comment by kingrty** [comment]
<img width="802" alt="Screen Shot 1400-11-30 at 05 58 11" src="https://user-images.githubusercontent.com/99199271/154782613-83cd0da8-ccbb-497d-aa72-f94550d73700.png">

**Comment by efroemling** [comment]
> I sent here

Oh wow; well, its clear there is a problem 😅.
I just uploaded a newer build (20469) to https://tools.ballistica.net/builds - can you try it? It prints more information about the errors. Also can you press the 'copy' button at the top right of the window and then paste the text here instead of sending a screenshot? Some important info is cut off in the screenshot.

Hopefully that will be enough for me to fix whatever is going wrong. Thanks for the help with this.

**Comment by kingrty** [comment]
> > I sent here
> 
> Oh wow; well, its clear there is a problem 😅. I just uploaded a newer build (20469) to https://tools.ballistica.net/builds - can you try it? It prints more information about the errors. Also can you press the 'copy' button at the top right of the window and then paste the text here (or send it to [support@froemling.net](mailto:support@froemling.net)) instead of sending a screenshot? Some important info is cut off in the screenshot.
> 
> Hopefully that will be enough for me to fix whatever is going wrong. Thanks for the help with this.
can't copy Clipboard error in this platform

**Comment by kingrty** [comment]
[Uploading Screen Shot 1400-11-30 at 22.06.53.pdf…]()

**Comment by efroemling** [comment]
Oh crap; you're right. Apparently clipboard stuff isn't enabled in those particular test builds. I'll get that fixed and push a new build in a bit. Sorry about that 🤦🏼‍♂️.

**Comment by kingrty** [comment]
[bs.zip](https://github.com/efroemling/ballistica/files/8102816/bs.zip)

**Comment by efroemling** [comment]
Ok, build 20472 is now up on [the builds page](https://tools.ballistica.net/builds). The copy button should now work. Can you paste me the output? Then I can hopefully finally fix this.

**Comment by kingrty** [comment]
> Ok, build 20472 is now up on [the builds page](https://tools.ballistica.net/builds). The copy button should now work. Can you paste me the output? Then I can hopefully finally fix this.

Running network diagnostics...
ua: BombSquad 1.6.9 TstB (20472) (x86_64_macos; reza’s MacBook Air; en_IR)
time: 2022-02-21 05:06:09.007368+00:00.

Contacting V1 master-server (https://legacy.ballistica.net)...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 174, in <lambda>
    _print_test_results(lambda: _test_fetch(baseaddr))
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 272, in _test_fetch
    response = urllib.request.urlopen(urllib.request.Request(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1298, in _send_request
    self.putheader(hdr, value)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1230, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 48: ordinal not in range(256)
Failed in 0.01s.

Contacting V1 alt master-server (https://acrobattleserver.appspot.com)...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 181, in <lambda>
    _print_test_results(lambda: _test_fetch(baseaddr))
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 272, in _test_fetch
    response = urllib.request.urlopen(urllib.request.Request(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1298, in _send_request
    self.putheader(hdr, value)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1230, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 48: ordinal not in range(256)
Failed in 0.01s.

Running V1 transaction...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 262, in _test_v1_transaction
    raise RuntimeError('timed out')
RuntimeError: timed out
Failed in 10.00s.

Contacting V2 master-server (https://tools.ballistica.net)...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 189, in <lambda>
    _print_test_results(lambda: _test_fetch(baseaddr))
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 272, in _test_fetch
    response = urllib.request.urlopen(urllib.request.Request(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1298, in _send_request
    self.putheader(hdr, value)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/http/client.py", line 1230, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 48: ordinal not in range(256)
Failed in 0.01s.

Checking nearest V2 region ping (-)...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 202, in <lambda>
    _print_test_results(lambda: _test_nearby_region_ping(nearest_region))
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 287, in _test_nearby_region_ping
    raise RuntimeError('No nearest region.')
RuntimeError: No nearest region.
Failed in 0.00s.

Diagnostics complete. Some diagnostics failed.

**Comment by efroemling** [comment]
Ok, thanks for sending that. I've figured out what the problem was and pushed a fix. Grab build 20477 from the [builds](https://tools.ballistica.net/builds) page and give it a try. I'm hopeful everything will work for you 🤞.

**Comment by kingrty** [comment]
> Ok, thanks for sending that. I've figured out what the problem was and pushed a fix. Grab build 20477 from the [builds](https://tools.ballistica.net/builds) page and give it a try. I'm hopeful everything will work for you now🤞.

Thank you very much, it works, but with VPN ....

**Comment by kingrty** [comment]
Running network diagnostics...
ua: BombSquad 1.6.9 TstB (20477) (x86_64_macos; rezas MacBook Air; en_IR)
time: 2022-02-21 18:15:15.281922+00:00.

Contacting V1 master-server (https://legacy.ballistica.net)...
Succeeded in 0.96s.

Contacting V1 alt master-server (https://acrobattleserver.appspot.com)...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 181, in <lambda>
    _print_test_results(lambda: _test_fetch(baseaddr))
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 272, in _test_fetch
    response = urllib.request.urlopen(urllib.request.Request(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Failed in 0.62s.

Running V1 transaction...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 262, in _test_v1_transaction
    raise RuntimeError('timed out')
RuntimeError: timed out
Failed in 10.00s.

Contacting V2 master-server (https://tools.ballistica.net)...
Succeeded in 1.57s.

Checking nearest V2 region ping (me-south-1: 109ms)...
Succeeded in 0.00s.

Diagnostics complete. Some diagnostics failed.

**Comment by efroemling** [comment]
Interesting. I'm assuming that last log you sent is *without* the VPN?
One of the V1 master-server addresses appears to be blocked in those results, but the other one seems to be working, so I would expect the V1-transaction-test to work, which would mean that the game itself should work. The fact that the transaction fails might mean my code needs to be fixed. So if you don't mind, I might tweak the diagnostics a bit and have you try running one more build. I'm hopeful I can get things fully working for you without needing a VPN.

Also, if you want to confirm that one of the addresses is in fact blocked from where you are, try to the following 2 urls in a web browser. If they are not blocked, they should print simply 'pong'. From the diagnostic I would expect the first to work for you but not the second.
https://legacy.ballistica.net/ping
https://acrobattleserver.appspot.com/ping

**Comment by kingrty** [comment]
https://legacy.ballistica.net/ping.  pong

**Comment by kingrty** [comment]
<img width="1256" alt="Screen Shot 1400-12-02 at 23 04 15" src="https://user-images.githubusercontent.com/99199271/155016808-71119c0a-c9d5-4f3e-bda4-8386e9bd92d2.png">

**Comment by efroemling** [comment]
Thanks; that lines up with what the game is seeing. 👍
I'll get a new build up soon which will hopefully route all communication through the first address which means things should work for you without a VPN.

**Comment by efroemling** [comment]
Ok, one more round :)
Build 20480 is up on the [builds page](https://tools.ballistica.net/builds). Can you try it paste me the diagnostics output? Also please let me know if it is still not working without the VPN.

**Comment by kingrty** [comment]
thanks eric its fix 
haha was hard problem you fixing 
you is best❤️

**Comment by efroemling** [comment]
Glad to hear it is fixed 😅.
If you have a moment, can you still send me the diagnostic output from the 20480 build? It might help me make sure I've fixed things in the correct way.

**Comment by kingrty** [comment]
yes sure

**Comment by kingrty** [comment]
Running network diagnostics...
ua: BombSquad 1.6.9 TstB (20480) (x86_64_macos; rezas MacBook Air; en_IR)
time: 2022-02-21 23:09:08.093327+00:00.

Contacting V1 master-server (https://legacy.ballistica.net)...
Succeeded in 0.78s.

Contacting V1 alt master-server (https://acrobattleserver.appspot.com)...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 181, in <lambda>
    _print_test_results(lambda: _test_fetch(baseaddr))
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 277, in _test_fetch
    response = urllib.request.urlopen(urllib.request.Request(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Failed in 0.33s.

V1-test-log: none succeeded; defaulting to s0

Current V1 address: https://legacy.ballistica.net

Running V1 transaction...
Succeeded in 1.01s.

Contacting V2 master-server (https://tools.ballistica.net)...
Succeeded in 1.34s.

Checking nearest V2 region ping (me-south-1: 109ms)...
Succeeded in 0.00s.

Diagnostics complete. Some diagnostics failed.

**Comment by efroemling** [comment]
Even though I'm glad it's working, there is still one bit of the diagnostic output that worries me.
`V1-test-log: none succeeded; defaulting to s0`

This means that when the game tested both v1 master-servers to see which one to use, neither attempt succeeded, and it just happened to default to using the first (which we know is actually working).

Could I ask you to grab the latest [build](https://tools.ballistica.net/builds) (20484) and show me the diagnostics output once more? I've added more logging to see why this is happening so I can hopefully fix that part to be more bulletproof.

I really appreciate all of your help with this stuff..

**Comment by kingrty** [comment]
Running network diagnostics...
ua: BombSquad 1.6.9 TstB (20484) (x86_64_macos; rezas MacBook Air; en_IR)
time: 2022-02-22 18:07:23.371779+00:00.

Contacting V1 master-server src0 (https://legacy.ballistica.net)...
Succeeded in 0.67s.

Contacting V1 master-server src1 (https://acrobattleserver.appspot.com)...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 181, in <lambda>
    _print_test_results(lambda: _test_fetch(baseaddr))
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 280, in _test_fetch
    response = urllib.request.urlopen(urllib.request.Request(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Failed in 0.45s.

V1-test-log: none succeeded in {stot:.3f}; defaulting to src0

V1 src0 result: {'t': '1645553216.600281'}

V1 src1 result: Traceback (most recent call last):
  File "<string>", line 80, in run
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Using V1 address: https://legacy.ballistica.net

Running V1 transaction...
Succeeded in 0.97s.

Contacting V2 master-server (https://tools.ballistica.net)...
Succeeded in 0.80s.

Checking nearest V2 region ping (me-south-1: 111ms)...
Succeeded in 0.00s.

Diagnostics complete. Some diagnostics failed.

**Comment by kingrty** [comment]
you're welcome 

A question to run the game at 120 Hz what system requirements?
i mean hardware

**Comment by efroemling** [comment]
> A question to run the game at 120 Hz what system requirements? i mean hardware

I'm using one of the new MacBook Pros with a 120hz ProMotion screen, and the Mac test build runs at 120 on it (though sometimes it seems to be around 80 in windowed mode; I need to look into that). 

I believe the cmake/prefab builds are currently hard-coded to 60hz, but it shouldn't be too hard to fix that to get them running at higher rates. I just haven't had a chance to look into that yet. It probably wouldn't be too hard to do if anyone wants to experiment.

**Comment by efroemling** [comment]
Ok, I'm 

> you're welcome

Ok, I think I've got everything working as it should. Could I have you send me logs from one last [build](https://tools.ballistica.net/builds) to make sure? (it is still build 20484, but technically it is a new build).

I'm 99% sure this is the last time I'll have to ask you :)

**Comment by kingrty** [comment]
I have a MacBook M1 when vertical sync is off going to 120hz but i see little laggy 

i ready for test

**Comment by kingrty** [comment]
Running network diagnostics...
ua: BombSquad 1.6.9 TstB (20484) (x86_64_macos; rezas MacBook Air; en_IR)
time: 2022-02-22 19:06:55.009165+00:00.

Contacting V1 master-server src0 (https://legacy.ballistica.net)...
Succeeded in 0.79s.

Contacting V1 master-server src1 (https://acrobattleserver.appspot.com)...
Traceback (most recent call last):
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 181, in <lambda>
    _print_test_results(lambda: _test_fetch(baseaddr))
  File "/Applications/BombSquadTest.app/Contents/Resources/ba_data/python/bastd/ui/settings/nettesting.py", line 280, in _test_fetch
    response = urllib.request.urlopen(urllib.request.Request(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Failed in 0.94s.

V1-test-log: only src0 succeeded in {stot:.3f}; using src0

V1 src0 result: {'t': '1645556807.8137789'}

V1 src1 result: Traceback (most recent call last):
  File "<string>", line 80, in run
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Applications/BombSquadTest.app/Contents/Resources/pylib/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Using V1 address: https://legacy.ballistica.net

Running V1 transaction...
Succeeded in 0.84s.

Contacting V2 master-server (https://tools.ballistica.net)...

**Comment by Dliwk** [comment]
> ```
> Running network diagnostics...
> ```
> [...]

Did you miss anything? it just looks a little cropped

**Comment by efroemling** [comment]
> > ```
> > Running network diagnostics...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [...]
> 
> 
> Did you miss anything? it just looks a little cropped

No that's the full output. I just have it print '...' to show that it's an ongoing operation.

**Comment by efroemling** [comment]
Everything looks good in the latest output. 😄  Again, thanks so much @kingrty for the help getting this fixed.

**Comment by Dliwk** [comment]
> No that's the full output. I just have it print '...' to show that it's an ongoing operation.

That means output was copied when diagnostic haven't fully finished? I'm confused a bit.

**Comment by efroemling** [comment]
> > No that's the full output. I just have it print '...' to show that it's an ongoing operation.
> 
> That means output was copied when diagnostic haven't fully finished? I'm confused a bit.

Oh; I thought you were just asking bout that particular line. There definitely should be more output than that. 😳

**Comment by efroemling** [comment]
> > No that's the full output. I just have it print '...' to show that it's an ongoing operation.
> 
> That means output was copied when diagnostic haven't fully finished? I'm confused a bit.

Basically the diagnostics just run _run_diagnostics() from bastd.ui.settings.nettesting in a background thread. It has a _print() call that it uses to send output to the window as the tests finish.  If you have a second, could you throw a few regular prints() in there to see what is happening? (I'm assuming you're testing this on linux?)

**Comment by efroemling** [comment]
> I have a MacBook M1 when vertical sync is off going to 120hz but i see little laggy
> 
> i ready for test

When you say you see a little lag, do you mean when vertical sync is off and it is running at 120hz? Or when it is on?

Also, to confirm: this is a regular M1 Mac with a 60hz monitor?

**Comment by Dliwk** [comment]
> Basically the diagnostics just run _run_diagnostics() from bastd.ui.settings.nettesting in a background thread. It has a _print() call that it uses to send output back to the game thread for display in the window as each test finishes. If you have a second, could you throw a few regular prints() in there to see what is failing or getting stuck? (I'm assuming you're testing this on linux?)

Everything seems to be fine there.. 
![image](https://user-images.githubusercontent.com/47295209/155211175-a767a431-7ada-429e-b3bf-905f46ebe990.png)

..so I assumed that @kingrty copied output too early (for example, I pressed `copy` button before final result and there is what I got)

```
Running network diagnostics...
ua: BallisticaCore 1.6.9 TstB (20480) (x86_64_linux; BallisticaCore Game; ru_RU.UTF-8)
time: 2022-02-22 20:09:48.878607+00:00.

Contacting V1 master-server (https://legacy.ballistica.net)...
Succeeded in 0.45s.

Contacting V1 alt master-server (https://acrobattleserver.appspot.com)...
Succeeded in 0.40s.

V1-test-log: both succeeded (0.403s, 0.403s); using s0

Current V1 address: https://legacy.ballistica.net

Running V1 transaction...
```

**Comment by efroemling** [comment]
> ..so I assumed that @kingrty copied output too early (for example, I pressed `copy` button before final result and there is what I got)

Oh.. so I guess he posted a one-line one and then edited his post and added the full output? I didn't see the original single-line one which led to me being confused about what you were asking about 😅. And yeah it could have been the result of pressing 'copy' too quickly.

**Comment by Dliwk** [comment]
> Oh.. so I guess he posted a one-line one and then edited his post and added the full output? I didn't see the original single-line one which led to me being confused about what you were asking about sweat_smile. And yeah it could have been the result of pressing 'copy' too quickly.

Haha, this is getting ridiculous :man_facepalming: We finally need to understand each other.

- It's me reduced quote to single line due not to take so much space. (though I placed `[...]` in quite wrong place which seems to confuse you)
- I though this output was not the full because of *last* line (`Contacting V2 master-server (https://tools.ballistica.net)...`)

**Comment by efroemling** [comment]
> Haha, this is getting ridiculous 🤦‍♂️ We finally need to understand each other.

Hahaha ok (taking a deep breath). I think I understand completely now. 🤦🏼‍♂️

**Comment by kingrty** [comment]
> > I have a MacBook M1 when vertical sync is off going to 120hz but i see little laggy
> > i ready for test
> 
> When you say you see a little lag, do you mean when vertical sync is off and it is running at 120hz? Or when it is on?
> 
> Also, to confirm: this is a regular M1 Mac with a 60hz monitor?

 yes when vertical sync is off 
yes 60hz monitor

**Comment by efroemling** [comment]
Since it looks like the main problem here is solved, I'll go ahead and close this. @kingrty please open a new issue if you'd like to further discuss other things like frame-rate issues. (I'd love to get the game running as smoothly as possible at any refresh rate)
