### ISSUE TITLE
Cannot start bombsquad server on raspberry pi


### ISSUE THREAD

**Issue by Loup-Garou911XD** [efroemling/ballistica#520]
Bombsquad server v1.7.9 for rpi
> Python 3.10.7 on linux
`
BombSquad server manager 1.3.1 starting up (opt mode)...
Interactive mode enabled; use the 'mgr' object to interact with the server.
Type 'help(mgr)' for more information.
>>> Valid server config file loaded.
Launching server subprocess...
Traceback (most recent call last):
  File "<string>", line 30, in <module>
  File "/home/myuser/bombsquad/BombSquad_Server_RaspberryPi_1.7.9/dist/ba_data/python/ba/__init__.py", line 21, in <module>
    from ba._activity import Activity
  File "/home/myuser/bombsquad/BombSquad_Server_RaspberryPi_1.7.9/dist/ba_data/python/ba/_activity.py", line 15, in <module>
    from ba._general import Call, verify_object_death
  File "/home/myuser/bombsquad/BombSquad_Server_RaspberryPi_1.7.9/dist/ba_data/python/ba/_general.py", line 9, in <module>
    import random
  File "/usr/local/lib/python3.10/random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
FATAL ERROR: Unhandled exception in logic thread:
Error in ba Python bootstrapping. See log for details.
terminate called after throwing an instance of 'std::logic_error'
  what():  Error in ba Python bootstrapping. See log for details.
Server subprocess exited with code -6.
Stopping subprocess...
Subprocess stopped.
Valid server config file loaded.
Launching server subprocess...
`

**Comment by Loup-Garou911XD** [comment]
Python compiled from source code on rpi 4

**Comment by ritiek** [comment]
I have a similar error on rpi zero w on executing the rpi server build 1.7.10 from https://tools.ballistica.net/downloads when python 3.10 is compiled from source (as it's not available on apt yet):
```python
$ ./bombsquad_server
BombSquad server manager 1.3.1 starting up (opt mode)...
Interactive mode enabled; use the 'mgr' object to interact with the server.
Type 'help(mgr)' for more information.
>>> Valid server config file loaded.
Launching server subprocess...
Traceback (most recent call last):
  File "<string>", line 30, in <module>
  File "/home/pi/BombSquad_Server_RaspberryPi_1.7.10/dist/ba_data/python/ba/__init__.py", line 21, in <module>
    from ba._activity import Activity
  File "/home/pi/BombSquad_Server_RaspberryPi_1.7.10/dist/ba_data/python/ba/_activity.py", line 15, in <module>
    from ba._general import Call, verify_object_death
  File "/home/pi/BombSquad_Server_RaspberryPi_1.7.10/dist/ba_data/python/ba/_general.py", line 9, in <module>
    import random
  File "/usr/local/lib/python3.10/random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: /usr/local/lib/python3.10/lib-dynload/math.cpython-310-arm-linux-gnueabihf.so: undefined symbol: PyFloat_Type
FATAL ERROR: Unhandled exception in logic thread:
Error in ba Python bootstrapping. See log for details.
terminate called after throwing an instance of 'std::logic_error'
  what():  Error in ba Python bootstrapping. See log for details.
Server subprocess exited with code -6.
Stopping subprocess...
Subprocess stopped.
```

**Comment by ritiek** [comment]
(also dupe of #269 and #481)

**Comment by Dliwk** [comment]
Oh no sorry I was about to write here something a long ago but I forgot about it.

Seems like deadsnakes ppa stuff doesn't work on raspberry pi and yeah similar problem was discussed in these issues.

**Comment by Loup-Garou911XD** [comment]
Update:test build working,server build still not working
https://media.discordapp.net/attachments/588424130647294128/1089399757140672542/2023-03-26-093454_1920x1080_scrot.png

**Comment by Loup-Garou911XD** [comment]
Update: I build server from source and it's working
Still don't know why official build won't work

**Comment by EraOSBeta** [comment]
> Update: I build server from source and it's working
> Still don't know why official build won't work

Is this still the case?

**Comment by Loup-Garou911XD** [comment]
> > Update: I build server from source and it's working
> > Still don't know why official build won't work
> 
> Is this still the case?

I hope so
Haven't tried for a long time
