### ISSUE TITLE
spinoff error

### ISSUE THREAD

**Issue by xujianing12** [efroemling/ballistica#607]
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Python_INCLUDE_DIRS Python_LIBRARIES
  Development Development.Module Development.Embed) (Required is exact
  version "3.11")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindPython/Support.cmake:3180 (find_package_handle_standard_args)
  /usr/share/cmake-3.22/Modules/FindPython.cmake:519 (include)
  CMakeLists.txt:35 (find_package)

-- Configuring incomplete, errors occurred!
See also "/mnt/c/Users/xlyfh/ballistica/build/spinofftest/core/build/cmake/server-debug/dist/CMakeFiles/CMakeOutput.log".
make[2]: *** [Makefile:1046: cmake-server-binary] Error 1
make[2]: Leaving directory '/mnt/c/Users/xlyfh/ballistica/build/spinofftest/core'
Traceback (most recent call last):
  File "/mnt/c/Users/xlyfh/ballistica/build/spinofftest/core/./tools/pcommand", line 135, in <module>
    pcommand_main(globals())
  File "/mnt/c/Users/xlyfh/ballistica/build/spinofftest/core/tools/efrotools/pcommand.py", line 66, in pcommand_main
    funcs[sys.argv[1]]()
  File "/mnt/c/Users/xlyfh/ballistica/build/spinofftest/core/tools/batools/pcommand.py", line 927, in gen_dummy_modules
    generate_dummy_modules(projroot=str(PROJROOT))
  File "/mnt/c/Users/xlyfh/ballistica/build/spinofftest/core/tools/batools/dummymodule.py", line 927, in generate_dummy_modules
    binary_path = apprun.acquire_binary(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/xlyfh/ballistica/build/spinofftest/core/tools/batools/apprun.py", line 174, in acquire_binary
    subprocess.run(binary_build_command, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', 'cmake-server-build']' returned non-zero exit status 2.
Command 'rm -rf build/dummymodules && ./tools/pcommand gen_dummy_modules' returned non-zero exit status 1.
make[1]: *** [Makefile:155: dummymodules] Error 1
make[1]: Leaving directory '/mnt/c/Users/xlyfh/ballistica/build/spinofftest/core'
Traceback (most recent call last):
  File "/mnt/c/Users/xlyfh/ballistica/tools/pcommand", line 135, in <module>
    pcommand_main(globals())
  File "/mnt/c/Users/xlyfh/ballistica/tools/efrotools/pcommand.py", line 66, in pcommand_main
    funcs[sys.argv[1]]()
  File "/mnt/c/Users/xlyfh/ballistica/tools/batools/pcommand2.py", line 310, in spinoff_test
    batools.spinoff.spinoff_test(sys.argv[2:])
  File "/mnt/c/Users/xlyfh/ballistica/tools/batools/spinoff/_test.py", line 148, in spinoff_test
    subprocess.run(
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['make', 'mypy']' returned non-zero exit status 2.
make: *** [Makefile:609: spinoff-test] Error 1

I recieved this when i try to 'make spinoff-test'

**Comment by xujianing12** [comment]
i use windows 11

**Comment by xujianing12** [comment]
I try 'make mypy', it shows:

Traceback (most recent call last):
  File "/mnt/c/Users/xlyfh/ballistica/./tools/pcommand", line 135, in <module>
    pcommand_main(globals())
  File "/mnt/c/Users/xlyfh/ballistica/tools/efrotools/pcommand.py", line 66, in pcommand_main
    funcs[sys.argv[1]]()
  File "/mnt/c/Users/xlyfh/ballistica/tools/batools/pcommand.py", line 927, in gen_dummy_modules
    generate_dummy_modules(projroot=str(PROJROOT))
  File "/mnt/c/Users/xlyfh/ballistica/tools/batools/dummymodule.py", line 927, in generate_dummy_modules
    binary_path = apprun.acquire_binary(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/xlyfh/ballistica/tools/batools/apprun.py", line 176, in acquire_binary
    raise RuntimeError(
RuntimeError: Binary not found at expected path 'build/prefab/full/windows_x86_server/release/dist/ballisticakit_headless'.
Command 'rm -rf build/dummymodules && ./tools/pcommand gen_dummy_modules' returned non-zero exit status 1.
make: *** [Makefile:155: dummymodules] Error 1

i never received this before...
